CREATE DATABASE QLCHTS
GO
USE QLCHTS
GO
--drop database QLCHTS
CREATE TABLE NHANVIEN(
MANV VARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
NGAYSINH DATE,
CCCD VARCHAR(20) NOT NULL,
SDT VARCHAR(15) NOT NULL,
GIOITINH BIT NOT NULL,
USERNAME VARCHAR(30)NOT NULL ,
PASSWORD VARCHAR(30)NOT NULL,
ROLE BIT NOT NULL,
TRANGTHAI BIT,
GHICHU NVARCHAR(100)
)
insert into NHANVIEN values ('001',N'Hoang','02/01/2021','123556913784','0387490000',1,'hoang01','123',0,0,N'Khong')
insert into NHANVIEN values ('002',N'Hoang','02/01/2021','123556913784','0387490000',1,'hoang02','123',0,1,N'Khong')
insert into NHANVIEN values ('003',N'ADMIN','02/01/2021','123556913784','0387490000',1,'ADMIN','ADMIN',1,1,N'Khong')

CREATE TABLE KhachHang(
MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
SDT VARCHAR(12) ,
GIOITINH BIT ,
DIACHI NVARCHAR(50),
GHICHU NVARCHAR(100),
TRANGTHAI BIT NOT NULL
)

Insert into khachhang values ('001',N'Nam','0123456789',N'',N'Vĩnh Phúc',N'',0)
Insert into khachhang values ('002',N'Mạnh','0123456789',N'',N'Hà Nội',N'',0)
Insert into khachhang values ('003',N'Hiếu','0123456789',N'',N'Hải Phòng',N'',0)
Insert into khachhang values ('004',N'Thúy','0123456789',N'',N'Hải Dương',N'',0)

CREATE TABLE HOADON(
MAHD varchar(10)  PRIMARY KEY,
MANV VARCHAR(10),
MAKH VARCHAR(10),
NGAYGD DATETIME ,
HINHTHUCTHANHTOAN BIT,
HINHTHUCMUA BIT,
KHACHTRA MONEY,
TONGTIEN MONEY,
TRANGTHAIHD NVARCHAR(30)
)
select * from HOADON

Insert into HOADON values ('001','002','003','03/02/2021',0,0,1200000,1200000,'')

print GETDATE()
CREATE TABLE DOITRA(
MAPDT VARCHAR(10) NOT NULL,
MAHD VARCHAR(10) NOT NULL,
MASP VARCHAR(10) NOT NULL,
HINHTHUC BIT NOT NULL,
LYDO NVARCHAR(100),
GHICHU NVARCHAR(100),
THOIGIAN datetime,
CONSTRAINT PK_DOITRA PRIMARY KEY (MAPDT)  
);
CREATE TABLE HOADONCHITIET(
MaSP varchar(10) not null,
MaHD varchar(10) not null,
SoLuong int not null,
TienCong money,
DonGia money not null,
GiamGia money,
ThanhTien money not null
CONSTRAINT HOADONCHITIET_Pk PRIMARY KEY (MAHD, MaSP)
);
CREATE TABLE DANHMUCSANPHAM(
MADM    VARCHAR(10) PRIMARY KEY,
TENDM   NVARCHAR(30),
MOTA    NVARCHAR(50),
TRANGTHAI BIT
)
INSERT INTO DANHMUCSANPHAM VALUES
('VT',N'VÒNG TAY','',0)

CREATE TABLE CHATLIEU(
MACL   VARCHAR(10) PRIMARY KEY,
TENCL  NVARCHAR(50),
TRANGTHAI   BIT,
MOTA   NVARCHAR(50)
)
INSERT INTO CHATLIEU VALUES
('GOLD',N'VÀNG','0',N'KHÔNG')
CREATE TABLE LOAICHATLIEU(
MALCL   VARCHAR(10) PRIMARY KEY,
MACL   VARCHAR(10),
TENLCL  VARCHAR(50),
GIABANRA MONEY,
GIAMUAVAO MONEY,
TUOI     INT
)
INSERT INTO LOAICHATLIEU VALUES
('18K','GOLD',N'VÀNG 18K','4000000','3000000',7500)
CREATE TABLE SANPHAM(
MASP         VARCHAR(10) PRIMARY KEY,
MALCL        VARCHAR(10),
MADM         VARCHAR(10),
TENSP        NVARCHAR(50),
KHOILUONG    FLOAT,
GIABAN       MONEY,
GiAMUAVAO    MONEY,
TIENCONG     MONEY,
TRANGTHAI    NVARCHAR(30),
SOLUONG      INT,
MOTA         NVARCHAR(50)
)
INSERT INTO SANPHAM VALUES 
('SP001','18K','VT',N'VÒNG TAY 18K','2','2','2','2',N'Đang bán','0',N'')


CREATE TABLE PHIEUNHAP(
MAPN               VARCHAR(10) PRIMARY KEY,
THANHTIEN          MONEY,
NGAYNHAP           DATE,
NOINHAP            NVARCHAR(50),
GHICHU             NVARCHAR(100),
)
CREATE TABLE CHITIETPHIEUNHAP(
MAPN      VARCHAR(10),
MASP      VARCHAR(10),
SL        INT ,
DONGIA    MONEY,
CONG      MONEY,
THANHTIEN MONEY,
);
ALTER TABLE HOADON  ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) 
ALTER TABLE HOADON  ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH) 
ALTER TABLE DOITRA  ADD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE HOADONCHITIET  ADD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD) 
ALTER TABLE HOADONCHITIET  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) 
ALTER TABLE SANPHAM  ADD FOREIGN KEY(MADM) REFERENCES DANHMUCSANPHAM(MADM) 
ALTER TABLE SANPHAM  ADD FOREIGN KEY(MALCL) REFERENCES LOAICHATLIEU(MALCL) 
ALTER TABLE LOAICHATLIEU  ADD FOREIGN KEY(MACL) REFERENCES CHATLIEU(MACL) 
ALTER TABLE CHITIETPHIEUNHAP  ADD FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN) 
ALTER TABLE CHITIETPHIEUNHAP  ADD FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP) 

go
CREATE PROC MA_SP_TUSINH
AS
BEGIN
DECLARE @MA_NEXT VARCHAR(20) --KHỞI TẠO BIẾN TỰ SINH
DECLARE @MAX INT --MAX LÀ TỔNG SỐ BẢN GHI HIỆN CÓ
SELECT @MAX =COUNT(MASP) +1 FROM SANPHAM WHERE MASP LIKE 'SP'
SET @MA_NEXT ='SP' +RIGHT('00' +CAST(@MAX AS VARCHAR(10)),10)
--KIỂM TRA MÃ TỒN TẠI
WHILE(EXISTS(SELECT MASP FROM SANPHAM WHERE MASP=@MA_NEXT))
BEGIN
     SET @MAX =@MAX+1
	 SET @MA_NEXT='SP' +RIGHT('00' +CAST(@MAX AS VARCHAR(10)),10)
END
SELECT @MA_NEXT as ma
END
go
CREATE PROC SP_MAHD
AS
BEGIN
DECLARE @MA_NEXT VARCHAR(20) --KHỞI TẠO BIẾN TỰ SINH
DECLARE @MAX INT --MAX LÀ TỔNG SỐ BẢN GHI HIỆN CÓ
SELECT @MAX =COUNT(MAHD) +1 FROM HOADON WHERE MAHD LIKE 'HD'
SET @MA_NEXT ='HD' +RIGHT('0' +CAST(@MAX AS VARCHAR(10)),10)
--KIỂM TRA MÃ TỒN TẠI
WHILE(EXISTS(SELECT MAHD FROM HOADON WHERE MAHD=@MA_NEXT))
BEGIN
     SET @MAX =@MAX+1
	 SET @MA_NEXT='HD' +RIGHT('0' +CAST(@MAX AS VARCHAR(10)),10)
END
SELECT @MA_NEXT as MAHD
END
--drop proc SP_MAHD
go

CREATE PROC SP_SEARCH @TENSP NVARCHAR(50)
AS
BEGIN
SELECT * FROM SANPHAM 
WHERE TENSP LIKE @TENSP
END 
GO 

--select *from HOADON


--select  hdct.MaSP,max(SoLuong) as so_luong_ban  from HOADONCHITIET hdct 

--SELECT top 5 sp.TENSP, SUM(hdct.SoLuong) AS TONG
--FROM SANPHAM sp,HOADONCHITIET hdct join HOADON hd on hd.MAHD =hdct.MaHD
--WHERE sp.MASP = hdct.MASP and DateDiff(dd,HD.NGAYGD,getdate())<1
--GROUP BY sp.TENSP
--ORDER BY SUM(hdct.SoLuong) DESC

--SELECT top 5 hdct.MaSP, SUM(hdct.SoLuong) AS TONG
--FROM HOADONCHITIET hdct join HOADON hd on hd.MAHD =hdct.MaHD
--WHERE  DateDiff(dd,HD.NGAYGD,getdate())<1
--GROUP BY hdct.MASP
--ORDER BY SUM(hdct.SoLuong) DESC

----------------------------------------------------------
--drop proc SP_BCTK1

CREATE PROC SP_BCTK1 @NGAYBATDAU DATETIME ,@NGAYKETTHUC DATETIME 
AS
BEGIN
SELECT TOP 5 SP.TENSP, SUM(HDCT.SOLUONG) AS TONG
FROM SANPHAM SP,HOADONCHITIET HDCT JOIN HOADON HD ON HD.MAHD =HDCT.MAHD
WHERE SP.MASP = HDCT.MASP AND HD.NGAYGD BETWEEN @NGAYBATDAU AND @NGAYKETTHUC--VÌ NẾU KO ĐỂ GIỜ THÌ SẼ LẤY 0H 
GROUP BY SP.TENSP
ORDER BY SUM(HDCT.SOLUONG) DESC
END
go
--exec SP_BCTK1 @NGAYBATDAU = '1/12/2021',@NGAYKETTHUC ='12/2/2021 23:59:59.999'
--exec SP_BCTK1 @NGAYBATDAU = 1/1/2021,@NGAYKETTHUC =12/2/2021 23:59:59.999''


--SELECT SUM(CT.SoLuong) FROM HOADONCHITIET CT INNER JOIN  SANPHAM sp ON CT.MaSP = sp.MASP 
--INNER JOIN DANHMUCSANPHAM DM ON sp.MADM =DM.MADM 
--inner join HOADON hd on hd.MAHD =ct.MaHD
--WHERE AND HD.NGAYGD BETWEEN @NGAYBATDAU AND @NGAYKETTHUC--VÌ NẾU KO ĐỂ GIỜ THÌ SẼ LẤY 0H

CREATE PROC SP_BCTK2 @NGAYBATDAU DATETIME ,@NGAYKETTHUC DATETIME ,@maDM varchar(20)
AS
BEGIN
SELECT SUM(CT.SoLuong) FROM HOADONCHITIET CT INNER JOIN  SANPHAM sp ON CT.MaSP = sp.MASP 
INNER JOIN DANHMUCSANPHAM DM ON sp.MADM =DM.MADM 
inner join HOADON hd on hd.MAHD =ct.MaHD
WHERE dm.MADM =@madm AND HD.NGAYGD BETWEEN @NGAYBATDAU AND @NGAYKETTHUC
END
go
--exec SP_BCTK2 @NGAYBATDAU = '06/01/2021',@NGAYKETTHUC ='12/04/2021 23:59:59.999',@madm =VT
--------------------------------------------------------------------------------------
CREATE PROC SP_BCTK3 @NGAYBATDAU DATETIME ,@NGAYKETTHUC DATETIME 
AS
BEGIN
SELECT  SUM(TONGTIEN) ,COUNT(HD.MAHD),SUM(GIAMGIA) FROM HOADON HD
JOIN HOADONCHITIET CT ON CT.MaHD =HD.MAHD
where HD.NGAYGD BETWEEN @NGAYBATDAU AND @NGAYKETTHUC
end
--exec SP_BCTK3 @NGAYBATDAU = '06/01/2021',@NGAYKETTHUC ='12/04/2021 23:59:59.999'

--SELECT  COUNT(HD.MAHD) FROM HOADON HD
--where HD.NGAYGD BETWEEN '06/01/2021'and '12/04/2021 23:59:59.999'

--select * from HOADON
--select SUM(TONGTIEN) from HOADON
--where HINHTHUCMUA =0
--where HINHTHUCMUA =1

--select SUM(TONGTIEN) from HOADON HD
--where HINHTHUCMUA =0 AND HD.NGAYGD BETWEEN '06/01/2021 ' AND '12/04/2021 23:59:59.999'

--select * from DANHMUCSANPHAM

--delete DANHMUCSANPHAM where MADM ='vt1'
go
CREATE PROC SP_MAPDT
AS
BEGIN
DECLARE @MA_NEXT VARCHAR(20) --KHỞI TẠO BIẾN TỰ SINH
DECLARE @MAX INT --MAX LÀ TỔNG SỐ BẢN GHI HIỆN CÓ
SELECT @MAX =COUNT(MAPDT) +1 FROM DOITRA WHERE MAPDT LIKE 'PDT'
SET @MA_NEXT ='PDT' +RIGHT('0' +CAST(@MAX AS VARCHAR(10)),10)
--KIỂM TRA MÃ TỒN TẠI
WHILE(EXISTS(SELECT MAPDT FROM DOITRA WHERE MAPDT=@MA_NEXT))
BEGIN
     SET @MAX =@MAX+1
     SET @MA_NEXT='PDT' +RIGHT('0' +CAST(@MAX AS VARCHAR(10)),10)
END
SELECT @MA_NEXT as MAPDT
END
go

CREATE PROC SP_MAPN
AS
BEGIN
DECLARE @MA_NEXT VARCHAR(20) --KHỞI TẠO BIẾN TỰ SINH
DECLARE @MAX INT --MAX LÀ TỔNG SỐ BẢN GHI HIỆN CÓ
SELECT @MAX =COUNT(MAPN) +1 FROM PHIEUNHAP WHERE MAPN LIKE 'PN'
SET @MA_NEXT ='PN' +RIGHT('0' +CAST(@MAX AS VARCHAR(10)),10)
--KIỂM TRA MÃ TỒN TẠI
WHILE(EXISTS(SELECT MAPN FROM PHIEUNHAP WHERE MAPN=@MA_NEXT))
BEGIN
     SET @MAX =@MAX+1
     SET @MA_NEXT='PN' +RIGHT('0' +CAST(@MAX AS VARCHAR(10)),10)
END
SELECT @MA_NEXT as MAPN
END